spring:
  application:
    name: service-zuul
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes:
    jurisdiction-service:
      paht: /jurisdiction-service/**
