server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: locahost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
